hello-world:
  image: tutum/hello-world
  ports:
    - 8080:80
  links:
    - link-world
  net: managed

hello-lb:
  image: rancher/load-balancer-service
  ports:
    - 80:80
  links:
    - hello-world
  net: managed

link-world:
  image: tutum/hello-world
  ports:
    - 8081:80
  net: managed

