hello-world:
# image changed to use nginx instead of tutum/hello-world
  image: nginx
  ports:
    - 8080:80
  links:
    - link-world
  net: managed

# add v2 hello world
hello-world-v2:
  image: tutum/hello-world
  ports:
    - 8082:80
  links:
    - link-world
  net: managed

hello-lb:
  image: rancher/load-balancer-service
  ports:
    - 80:80
  links:
    - hello-world
# add v2 hello world to lb
    - hello-world-v2
  net: managed

link-world:
  image: tutum/hello-world
  ports:
    - 8081:80
  net: managed

